"use client";

import { ArrowUp, Bot, BookOpen, RotateCcw, Sparkles } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";

type Message = { role: "assistant" | "user"; text: string; reference?: string };
const starters = ["Explain bonding vs. grounding", "Walk me through a load calculation", "Quiz me on Article 210"];

function responseFor(prompt: string): Message {
  const lower = prompt.toLowerCase();
  if (lower.includes("bond") || lower.includes("ground")) return { role:"assistant", text:"Think of grounding and bonding as doing different jobs. Grounding connects the electrical system to earth to stabilize voltage. Bonding connects conductive parts together to create a low-impedance fault-current path. On an exam question, ask: is this about earth/reference voltage, or getting fault current back to the source so the breaker opens?", reference:"Study path: NEC 250.4(A)(1) and 250.4(A)(5)" };
  if (lower.includes("load") || lower.includes("watt")) return { role:"assistant", text:"Start by listing each load and deciding whether it is continuous. Convert power to current when needed with I = P ÷ V. Apply the relevant demand factors, then size conductors and overcurrent protection as separate decisions. Keeping those steps separate prevents most exam mistakes.", reference:"Related: Articles 210, 215, and 220" };
  if (lower.includes("210") || lower.includes("branch")) return { role:"assistant", text:"Article 210 covers branch circuits. Focus first on ratings and conductor sizing, then required outlets, then GFCI and AFCI protection. I’d begin with this check: a continuous branch-circuit load is generally included at 125%. What makes a load continuous?", reference:"NEC 210.19(A) and 210.20(A)" };
  return { role:"assistant", text:"Let’s make it concrete. First identify the scope of the question, then locate the general rule, and finally check whether a more specific article or exception changes it. Tell me the equipment type, voltage, and what the question is asking you to size or protect.", reference:"WattWise code-navigation method" };
}

export function TutorChat({ initialPrompt = "" }: { initialPrompt?: string }) {
  const initial: Message[] = [{ role:"assistant", text:"Hey Tehron—I’m your code-aware study tutor. Ask about a concept, paste a practice question, or tell me what you want to review. I’ll keep the explanation focused and show you where to look next." }];
  if (initialPrompt) initial.push({role:"user",text:initialPrompt},responseFor(initialPrompt));
  const [messages,setMessages]=useState<Message[]>(initial);
  const [input,setInput]=useState("");
  function send(text=input){const clean=text.trim();if(!clean)return;setMessages(value=>[...value,{role:"user",text:clean},responseFor(clean)]);setInput("");}
  return <div className="flex min-h-[calc(100vh-68px)] flex-col bg-white"><div className="border-b border-[var(--line)] px-4 py-5 md:px-8"><div className="mx-auto flex max-w-[820px] items-center justify-between"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[var(--blue)] text-white"><Bot className="size-5"/></span><div><h1 className="text-sm font-semibold">WattWise Tutor</h1><p className="mt-0.5 flex items-center gap-1.5 text-[10px] text-[var(--ink-faint)]"><span className="size-1.5 rounded-full bg-[#36a06f]"/>Ready · Journeyman context</p></div></div><Button onClick={()=>setMessages([{role:"assistant",text:"Fresh page. What do you want to understand?"}])} variant="ghost" size="sm"><RotateCcw className="size-3.5"/>New chat</Button></div></div>
    <div className="app-scroll flex-1 overflow-y-auto px-4 py-8 md:px-8"><div className="mx-auto max-w-[760px] space-y-6">{messages.map((message,index)=><div key={index} className={`flex ${message.role==='user'?'justify-end':'justify-start'}`}>{message.role==='assistant'&&<span className="mr-3 mt-1 grid size-8 shrink-0 place-items-center rounded-lg bg-[var(--blue-soft)] text-[var(--blue)]"><Sparkles className="size-3.5"/></span>}<div className={`max-w-[85%] rounded-[20px] px-4 py-3 text-sm leading-6 md:max-w-[75%] ${message.role==='user'?'rounded-tr-md bg-[var(--ink)] text-white':'rounded-tl-md bg-[var(--surface)] text-[var(--ink)]'}`}><p>{message.text}</p>{message.reference&&<div className="mt-3 flex items-start gap-2 border-t border-black/5 pt-3 text-[10px] font-medium text-[var(--blue)]"><BookOpen className="mt-0.5 size-3 shrink-0"/>{message.reference}</div>}</div></div>)}{messages.length===1&&<div className="pt-2"><p className="mb-3 text-center text-[10px] font-bold uppercase tracking-[.13em] text-[var(--ink-faint)]">Try asking</p><div className="flex flex-wrap justify-center gap-2">{starters.map(item=><button onClick={()=>send(item)} key={item} className="rounded-full border border-[var(--line)] bg-white px-4 py-2 text-xs text-[var(--ink-soft)] hover:border-[var(--blue)] hover:text-[var(--blue)]">{item}</button>)}</div></div>}</div></div>
    <div className="sticky bottom-0 border-t border-[var(--line)] bg-white/95 px-4 py-4 backdrop-blur-xl md:px-8"><form onSubmit={(event)=>{event.preventDefault();send();}} className="mx-auto flex max-w-[760px] items-end gap-2 rounded-[20px] border border-[var(--line-strong)] bg-white p-2 shadow-[0_10px_35px_rgba(30,35,50,.08)]"><textarea rows={1} value={input} onChange={event=>setInput(event.target.value)} placeholder="Ask about a concept or practice question…" className="max-h-32 min-h-10 flex-1 resize-none bg-transparent px-3 py-2 text-sm leading-5 outline-none"/><Button type="submit" size="icon" aria-label="Send message"><ArrowUp className="size-4"/></Button></form><p className="mx-auto mt-2 max-w-[760px] text-center text-[9px] text-[var(--ink-faint)]">Study support, not field guidance. Verify current code and local amendments.</p></div>
  </div>;
}
